### ISSUE TITLE
jenkinsfile in private git repo not supported?

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#101]
Looking at the code here:
https://github.com/fabric8io/openshift-jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMapper.java#L86-L106

it would appear that any git credentials supplied in the BuildConfig are ignored and not used to retrieve the Jenkinsfile when the pipeline job runs.

Assuming that's correct, we need to add support for using the git credentials supplied in the buildconfig.

@jimmidyson

**Comment by bparees** [comment]
also tracked as https://bugzilla.redhat.com/show_bug.cgi?id=1390295

**Comment by jimmidyson** [comment]
@bparees Just to confirm that Jenkins will be able to view secrets as specified in the `sourceSecret` field?

**Comment by bparees** [comment]
@jimmidyson yes the jenkins service account should be able to retrieve the secrets referenced in sourceSecret.

**Comment by jimmidyson** [comment]
For source secrets what `type` can I expect on the secret? Assuming username/password & ssh key but not sure what the string names of those `type`s are?

**Comment by bparees** [comment]
@jimmidyson here's our docs that tell users how to define sourceSecrets, hopefully that addresses your question: https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds

our code for handling the various secrets is here:
https://github.com/openshift/origin/blob/master/pkg/build/builder/cmd/scmauth/scmauths.go

**Comment by jimmidyson** [comment]
OK I'll figure it out from that. Thanks!

**Comment by jimmidyson** [comment]
So looking through the OpenShift docs at https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds, I'm not sure the sync plugin will handle every scenario. Using username/password & ssh key creds will be fine, but adding trusted CA cert & gitconfig files are unlikely to be supported without significant investigation & probably updates to some other core Jenkins plugins (e.g. git plugin). Hope that's acceptable.

**Comment by bparees** [comment]
that probably gets us 90% of the way there, anyway.

**Comment by akram** [comment]
Hi guys,
I just felt in the remaining 10% : I need my Jenkins job to do scm checkout from a git server using private certificate, and it is not taking into account my custom certificate.

Any workaround ?
