### ISSUE TITLE
Failed to load initial buildconfigs

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#41]
Running a jenkins image w/ this plugin in the default namespace and having granted permissions to the default service account via:
`$ oc policy add-role-to-user edit system:serviceaccount:default:default`

I get this error in the jenkins logs on startup:

```
INFO: loading initial BuildConfigs resources
Apr 21, 2016 1:41:31 PM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration$1 run
SEVERE: Failed to load initial BuildConfigs: hudson.security.AccessDeniedException2: anonymous is missing the Job/Create permission
hudson.security.AccessDeniedException2: anonymous is missing the Job/Create permission
        at hudson.security.ACL.checkPermission(ACL.java:63)
        at hudson.model.Node.checkPermission(Node.java:463)
        at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:252)
        at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3096)
        at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:110)
        at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.onInitialBuildConfigs(BuildConfigWatcher.java:66)
        at io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration$1.run(GlobalPluginConfiguration.java:165)
```

@rawlingsj @jimmidyson

**Comment by bparees** [comment]
(I do have a valid pipeline strategy buildconfig defined in the default namespace)

**Comment by jimmidyson** [comment]
@bparees This is now fixed but before closing I want to update the s2i Jenkins image you're using. The snapshot is published to Sonatype snapshots repo - is there a way to get s2i scripts to use that for snapshot dependencies or shall I just manually copy it into plugins dir in the git repo for now?

**Comment by bparees** [comment]
@jimmidyson you could include a custom assemble script in the jenkins-s2i repo.  The custom assemble script should be a fork of the existing one in our jenkins image repo, but add your logic to pull the snapshot plugin.

your assemble script would go in ".s2i/bin" in this repo:
https://github.com/rawlingsj/openshift-jenkins-s2i-config

and the assemble script you'd fork is:
https://github.com/openshift/jenkins/blob/master/1/contrib/s2i/assemble

**Comment by jimmidyson** [comment]
OK might try that - for now it's copied in manually & works fine.

**Comment by bparees** [comment]
hm, i built a brand new jenkins image off the repo this morning and i'm seeing the same failure as before:
ion$1 run
SEVERE: Failed to load initial BuildConfigs: hudson.security.AccessDeniedException2: anonymous is missing the Job/Create permission
hudson.security.AccessDeniedException2: anonymous is missing the Job/Create permission

**Comment by bparees** [comment]
i'm building it via `s2i build https://github.com/rawlingsj/openshift-jenkins-s2i-config.git openshift/jenkins-1-centos7 fabric8/jenkins-openshift-pipeline:latest`

**Comment by jimmidyson** [comment]
Maybe it would help if I actually pushed the fixes... Try now.

**Comment by bparees** [comment]
> Maybe it would help if I actually pushed the fixes... Try now.

hard to believe that could have anything to do with it, but sure i'll try...

yup, looks like it's working now.  Thanks!
