### ISSUE TITLE
build stays in new state but has a started time

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#45]
I created a build and the sync plugin picked it up and appears to have set the "started" time but left the build in the "new" state.  I would have expected those two things to happen together.

eventually the build did enter the running state.

**Comment by bparees** [comment]
@jimmidyson

**Comment by bparees** [comment]
note, now that i have things working end to end i no longer see this behavior.  this can probably be closed, but i'd like confirmation that the sync logic won't update the start time when it's not updating the status to pending or running.

**Comment by jimmidyson** [comment]
This was a problem in the polling which is now fixed.
