### ISSUE TITLE
missing read permissions in build status message

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#46]
my build (which is now in the running state, as I would expect), shows this annotation on the build object itself:

 "openshift.io/jenkins-status-json": "\u003chtml\u003e\u003chead\u003e\u003cmeta http-equiv='refresh' content='1;url=/login?from=%2Fjenkins%2Fjob%2Fruby-sample-build%2F1%2Fwfapi%2Fdescribe'/\u003e\u003cscript\u003ewindow.location.replace('/login?from=%2Fjenkins%2Fjob%2Fruby-sample-build%2F1%2Fwfapi%2Fdescribe');\u003c/script\u003e\u003c/head\u003e\u003cbody style='background-color:white; color:white;'\u003e\n\n\nAuthentication required\n\u003c!--\nYou are authenticated as: anonymous\nGroups that you are in:\n  \nPermission you need to have (but didn't): hudson.model.Hudson.Read\n ... which is implied by: hudson.security.Permission.GenericRead\n ... which is implied by: hudson.model.Hudson.Administer\n--\u003e\n\n\u003c/body\u003e\u003c/html\u003e

**Comment by bparees** [comment]
@jimmidyson

**Comment by spadgett** [comment]
Seeing this as well.

<img width="872" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/1167259/14861608/fe4d2042-0c7b-11e6-9e14-e9ee864a77e9.png">

**Comment by spadgett** [comment]
Need to check response status code here:

https://github.com/fabric8io/openshift-jenkins-sync-plugin/blob/ebc8ad05c0bd717790d73c8970741b2c18ccfd59/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L193

**Comment by jimmidyson** [comment]
This has now changed in #47 to use the internal API rather than RESTful calls (much better idea!)
