### ISSUE TITLE
openshift.io/jenkins-log-url annotation uses http when my Jenkins uses https

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#49]
The log URL that is added to the build is

http://jenkins-default.router.default.svc.cluster.local/job/ruby-sample-build/3/consoleText

The correct URL for my environment uses https and should be

https://jenkins-default.router.default.svc.cluster.local/job/ruby-sample-build/3/consoleText

I haven't changed any of the defaults from the template.

@bparees @jwforres

**Comment by spadgett** [comment]
workaround is to set the insecure edge termination policy to redirect on the jenkins route in openshift

**Comment by spadgett** [comment]
@bparees can we add insecure policy redirect to the route in the template? i think we'd want it anyway

**Comment by bparees** [comment]
@spadgett sure, i've added it to my jenkinstemplate,json, for now you can just add it to your version but i'll make sure it's included in whatever we end up shipping.
