### ISSUE TITLE
builds processed out of order

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#52]
I created a bunch of pipeline build instances and it looks like build 10 was procesed before build 9:

```
sample-pipeline-10    JenkinsPipeline   Git@jfile     Running   About a minute ago   1m42s
sample-pipeline-3     JenkinsPipeline   Git@jfile     Failed    7 minutes ago        2s
sample-pipeline-4     JenkinsPipeline   Git           Failed    6 minutes ago        
sample-pipeline-5     JenkinsPipeline   Git@jfile     Failed    6 minutes ago        1s
sample-pipeline-6     JenkinsPipeline   Git@jfile     Failed    5 minutes ago        
sample-pipeline-7     JenkinsPipeline   Git@jfile     Failed    5 minutes ago        1m51s
sample-pipeline-8     JenkinsPipeline   Git@jfile     Failed    3 minutes ago        21s
sample-pipeline-9     JenkinsPipeline   Git@jfile     New                    
```

**Comment by jstrachan** [comment]
given builds are parallel, I'm not sure what you expect. Do you want to explicitly serialise all builds and lose the power of parallel building?

**Comment by jimmidyson** [comment]
The underlying problem is that if multiple identical build queued in Jenkins, they are consolidated into a single actual build that will execute. This means of there are multiple new openshift builds there is going to only be a single Jenkins build. Not quite sure how that should be handled. Set previous openshift builds to skipped perhaps?

**Comment by bparees** [comment]
> given builds are parallel, I'm not sure what you expect. Do you want to explicitly serialise all builds and lose the power of parallel building? 

what do you mean all builds are parallel?  jenkins runs them serially.  it's now explicitly running them serially and in the wrong order.

(also openshift now defaults to serial build execution for "normal" (non pipeline) builds).

**Comment by bparees** [comment]
> The underlying problem is that if multiple identical build queued in Jenkins, they are consolidated into a single actual build that will execute. This means of there are multiple new openshift builds there is going to only be a single Jenkins build. Not quite sure how that should be handled. Set previous openshift builds to skipped perhaps?

that doesn't appear to be what happened here...I created 10 openshift build objects (all in the new state) and as you can see from the output, there is a 1-2 minute spacing between each one being executed, so each one was executed/updated independently.

What i would expect the sync plugin to do:

1) query openshift for builds in the new state
2) pick the "oldest" one
3) execute/queue a jenkins pipeline job for it

whether the sync plugin also queues jobs for the rest of the builds, or waits until the current job completes before queuing the next one, doesn't matter, but it should be picking them based on creation time instead of what appears to be an alphabetical sort (which fails for numeric values).

**Comment by jimmidyson** [comment]
Shame there's no sorting in the kubernetes API... will look at ensuring oldest build gets picked.

> whether the sync plugin also queues jobs for the rest of the builds, or waits until the current job completes before queuing the next one

It doesn't make sense to queue the next one. Say you have 10 builds queued with no commit specified they will just pick HEAD which will result in probably duplicate Jenkins builds. Doesn't seem to make sense to me at least.

**Comment by bparees** [comment]
> It doesn't make sense to queue the next one. Say you have 10 builds queued with no commit specified they will just pick HEAD which will result in probably duplicate Jenkins builds. Doesn't seem to make sense to me at least.

it definitely depends on the scenario, which is why we created multiple policies in openshift.

If your pipeline is just building head, then sure, skipping over the intermediary builds and just running the latest makes sense.

if the pipeline took some parameters and is testing specific commits, i might want to kick off multiple executions are different commits because i actually want all the commits tested individually (in which case you'd probably want to run them in parallel too, ideally, but we can live without that)

**Comment by rawlingsj** [comment]
From a CD perspective I would expect to only ever build from master, if you want to build specific commits then maybe that's a separate CI job?

**Comment by bparees** [comment]
@rawlingsj I think we would anticipate people using these pipelines to implement CI flows, CD flows, and end to end CI+CD flows.

**Comment by jimmidyson** [comment]
Different input parameters (commits, etc) _should_ be treated as separate builds. It is only identical build requests that Jenkins consolidates.

**Comment by jimmidyson** [comment]
This should now be sorted, building from oldest. Discussion on build strategies, queuing, etc discussed in other issues.
