### ISSUE TITLE
Pipelines only run in default namespace

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#54]
Known issue, but opening here to discuss and track.

https://github.com/fabric8io/openshift-jenkins-s2i-config#todo

In a real deployment, only cluster admins would have access to this namespace. Even for demos, other stuff like the router and registry show up, which you don't want.

/cc @bparees @jimmidyson @fabianofranz

**Comment by bparees** [comment]
i've got it working in other namespaces as of last night, but you have to set a KUBERNETES_PROJECT env variable, as opposed to being able to set it in the jenkins config explicitly, currently.

instructions coming hopefully today.  trying to polish some other areas of the new directions.

**Comment by jimmidyson** [comment]
I assume the normal use case is to to handle BCs in the same namespace Jenkins runs in? We've just updated the fabric8 kubernetes client that this plugin uses under the covers to handle the upstream `/var/run/secrets/kubernetes.io/serviceaccount/namespace` which I assume OpenShift supports/will support soon? That defaults the namespace if that file is available.

**Comment by bparees** [comment]
> I assume the normal use case is to to handle BCs in the same namespace Jenkins runs in?

yes

> We've just updated the fabric8 kubernetes client that this plugin uses under the covers to handle the upstream /var/run/secrets/kubernetes.io/serviceaccount/namespace which I assume OpenShift supports/will support soon?

don't know... @smarterclayton any idea when openshift will pick this feature up?

regardless i think we'll still need a way for users who want to run the jenkins server in another project, or outside openshift entirely, to do configure this.

**Comment by jimmidyson** [comment]
>  i think we'll still need a way for users who want to run the jenkins server in another project, or outside openshift entirely, to do configure this.

Definitely but want to ensure that the default use case requires no configuration to make it easier to consume.

**Comment by bparees** [comment]
> Definitely but want to ensure that the default use case requires no configuration to make it easier to consume.

absolutely.

**Comment by smarterclayton** [comment]
OpenShift since v1.1.6 has supported namespace on disk via service account.

**Comment by bparees** [comment]
Even after we have defaulting such that we launch the pods in the same namespace as the jenkins master, we're probably going to want users to be able to configure the slave namespace at a per job level instead of only at the global config level.

**Comment by jimmidyson** [comment]
@bparees Separate issue for that please.

**Comment by bparees** [comment]
@jimmidyson what's the behavior going to be now?  If you leave the kubernetes namespace field blank then it'll default, otherwise it'll use the field value?

**Comment by bparees** [comment]
> @bparees Separate issue for that please. 

what repo? it seems like a feature for the kubernetes/slave-launched plugin, not the sync plugin.

**Comment by bparees** [comment]
@jimmidyson done: https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/63
