### ISSUE TITLE
Jenkins URL needs to be manually changed before pipelines run

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#55]
Per @bparees, there is a manual configuration step after the jenkins template is deployed:

> Go to manage jenkins
> Choose configure system
> Scroll down to the "Kubernetes" section within the "Cloud" section
> Update the port on the jenkins url to "8080"

Is it possible to set the right URL out of the box?

**Comment by bparees** [comment]
the next iteration of my instructions will setup the jenkins service on port 80 so this step isn't necessary.

**Comment by spadgett** [comment]
OK, thanks @bparees. Closing.
