### ISSUE TITLE
Script approvals needed for changes to build config Jenkinsfile

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#57]
A Jenkins admin needs to manually approve changes to Jenkinsfiles when they're inline in the build config. How important is this in the scenario where we have a dedicated Jenkins for each OpenShift namespace?

We might consider enabling Groovy sandboxing, possibly whitelisting operations from the OpenShift Jenkins plugin.

https://wiki.jenkins-ci.org/display/JENKINS/Script+Security+Plugin#ScriptSecurityPlugin-GroovySandboxing

I'm not sure if approvals are needed when the Jenkinsfile is in your Git repository.

/cc @jimmidyson @bparees @fabianofranz

**Comment by jimmidyson** [comment]
@rawlingsj Thoughts?

**Comment by bparees** [comment]
I started a thread on this last night, this was the answer so far from @rawlingsj:

```
You can add entries to the S2I config scriptApproval.xml so I think this is the best way to auto approve, easiest way is to manually approve in jenkins then oc exec into the jenkins image and look at $JENKINS_HOME/scriptApproval.xml to get the values.

As an example the fabric8 jenkins image which has the fabric8 CD scripts built in, auto approves a lot of scripts https://github.com/fabric8io/jenkins-docker/blob/master/config/scriptApproval.xml
```

**Comment by rawlingsj** [comment]
Yeah approvals are needed and I dont think you can enable the Groovy sandboxing when using the Jenkinsfile from an SCM.  

As @bparees mentioned we add pre-approved scripts to a scriptApproval.xml as we dont have persistence on our jenkins pod.  

We normally manually approve the scripts in jenkins when we're developing the functions then add them to our image.  With the fabric8 I've been meaning to change this so we mount them as a secret or volume rather than baking them into the image itself.

It might be worth reaching out to the Jenkins community to see if they have a better approach.

**Comment by jwforres** [comment]
Is it possible for the sync plugin to know that the script needs approval and write back onto the status message on the build config, the web console already reads that to show warnings when there are other kinds of issues.  Then we can at least point the user to the jenkins console to approve the script.

**Comment by bparees** [comment]
That's a question for @jimmidyson i think.  it's a good idea, since we probably won't be able to pre-approve everything someone might try to do in a script.

**Comment by jstrachan** [comment]
are we saying that we want a different set of access roles as to who can change a Jenkinsfile inside a BuildConfig versus who can change the rest of the BuildConfig? If so that sounds like the Jenkinsfile should not be embedded inside a BuildConfig and could be moved to a separate OpenShift resource than can have independent access control?

**Comment by jstrachan** [comment]
am generally confused if this issue is to do with approving changes to Jenkinsfiles; or approving the progress of a build ;)

BTW another option to enforce approval of changes to a Jenkinsfile is to just store them in git and prevent access to git and only allow PRs or gerrit code reviews etc

**Comment by jimmidyson** [comment]
All steps in Jenkinsfile need to be approved, one way or another, for Jenkins to actually run them. This is the standard way that Jenkins handles Groovy scripting. I haven't had a chance to see if it's possible to get required approvals from the Jenkins API &, even if it is, how to relate that to the build that requires the approval.

**Comment by jimmidyson** [comment]
Two options I can think of: 1) try to figure out how to use Groovy sandbox (if that provides enough freedom to do what users need); or 2) enable the Overall / RunScripts permission for accounts running jobs. Not sure how easy/feasible is to do but worth a try if we don't consider there to be any security issues with that.

**Comment by spadgett** [comment]
@jstrachan We're asking if we can disable the approvals. The way Jenkins is configured now, I have to login in as Jenkins user admin and approve any Jenkinsfile change under Manage Jenkins -> In-process Script Approval.

**Comment by jimmidyson** [comment]
Supposedly https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Groovy+Plugin enables the groovy sandbox by default since 2.2 - not that I'm sure we're using this plugin :) @rawlingsj? This may work around the issue of approvals.

**Comment by rawlingsj** [comment]
We're using that plugin except when I last updated to that latest pipeline plugins on fabric8 we had a few problems building certain types of projects.  

I'm hoping to figure that out and finish off the jenkins 2.0 upgrade once we have a few basic automated system tests in our CD pipeline.

FWIW I think this is that plugin https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/plugins.txt#L9

**Comment by jimmidyson** [comment]
Ah yeah that's the one. We're going to need to upgrade the plugins one way or another so we should probably try again with the updating ASAP.

**Comment by rawlingsj** [comment]
agreed - we needed automated tests ASAP as after the upgrade nodejs worked but springboot failed.  If we updated just the pipeline related plugins maybe we'll be alright.

FWIW I created a little java app to update a plugins.txt with the latest versions from the jenkins update center https://github.com/rawlingsj/jenkins-plugin-updater

**Comment by rawlingsj** [comment]
From @jimmidyson comment above
> Supposedly https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Groovy+Plugin enables the groovy sandbox by default since 2.2 - not that I'm sure we're using this plugin :) @rawlingsj? This may work around the issue of approvals.

This should be updated in the openshift jenkins plugins.txt https://github.com/openshift/jenkins/blob/master/1/contrib/openshift/base-plugins.txt#L16

**Comment by jwforres** [comment]
does anyone know if there was a reason we were using 2.0 and not 2.2 in the
openshift jenkins image  @bparees?

**Comment by rawlingsj** [comment]
When the original plugin list was created 2.0 was the latest version.

**Comment by rawlingsj** [comment]
The version numbers were taken from the tried and tested fabric8 jenkins image.  There have been a few Jenkins releases recently since their 2.0 release so the list that you have are not the latest.

**Comment by jwforres** [comment]
@rawlingsj ok thanks! devexp folks are working on updating the image

**Comment by gabemontero** [comment]
I'm going to do some sanity checks with the 2.2 versions, and if OK, I'll start a PR to update the openshift jenkins centos image to 2.2 for the pipeline stuff

**Comment by rawlingsj** [comment]
Ok - be aware I ran into an issue updating to the latest a little while back which I've reverted from the fabric8 jenkins image, it may only have affected our kubernetes-workflow plugin that you dont use mind.. https://github.com/fabric8io/jenkins-docker/issues/64

**Comment by gabemontero** [comment]
thanks for the heads up @rawlingsj - can't tell from just reading your issue if it will affect the new DSL I've put in for the openshift pipeline ... I should have some actual results to report shortly

**Comment by rawlingsj** [comment]
Ok cool - also incase it's useful I created a little java util to scan a plugins.txt and figure out the latest versions available in the jenkins update center https://github.com/rawlingsj/jenkins-plugin-updater

**Comment by gabemontero** [comment]
Not everyone of the workflow* plugins has version 2.2 posted on the jenkins update center yet.  So there will not be a generic upgrade to 2.2.

the pipeline+groovy+plugin or workflow-cps does have 2.2 available ... I'll try to upgrade just that and see if that passes some basic regressions

**Comment by gabemontero** [comment]
Cool - I'll give if a try when I get the chance.  Thanks.

**Comment by gabemontero** [comment]
regression testing held up OK ... see the above PR for update to openshift jenkins image

**Comment by jimmidyson** [comment]
I've upgraded workflow-cps plugin to 2.7 in our fabric8io/openshift-jenkins-s2i-config & this means that pipeline scripts run from SCM (git) will be run in groovy sandbox, so no approvals required. I have also updated this plugin in #80 to ensure that inline pipeline scripts are also run in groovy sandbox. I think that should mean we don't have to approve anything any more.

**Comment by bparees** [comment]
@spadgett @jimmidyson it looks like even with this change, we need to provide a whitelist:

```
To switch to this mode, simply check the box Use Groovy Sandbox below the Groovy script’s entry field. Sandboxed scripts can be run immediately by anyone. (Even administrators, though the script is subject to the same restrictions regardless of who wrote it.) When the script is run, every method call, object construction, and field access is checked against a whitelist of approved operations. If an unapproved operation is attempted, the script is killed and the corresponding Jenkins feature cannot be used yet.

The Script Security plugin ships with a small default whitelist, and integrating plugins may add operations to that list (typically methods specific to that plugin).
```

so we can add the openshift plugin signatures to the whitelist in our image, but it's still going to be problematic as soon as users go slightly off that path.

**Comment by ALRubinger** [comment]
@jimmidyson Could you comment on when we'd be seeing the "we don't have to approve anything any more" hit?  We're waiting on a release or a new image, or we need to upgrade to this version somewhere?

**Comment by jimmidyson** [comment]
As discussed above, my initial thought was wrong. Scripts are run in a sandbox but we still need to whitelist operations if they are outside the default list.
