### ISSUE TITLE
Can't cancel Jenkins strategy build from OpenShift

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#59]
Moved from https://github.com/openshift/origin/issues/8931

Can't cancel a pipeline build from OpenShift:

```
❯ oc cancel-build sample-pipeline-28 -n myproject
error: build myproject/sample-pipeline-28 failed to cancel: timed out waiting for the condition
error: failure during the build cancellation
```

Nothing appears to happen when I cancel a running Jenkins strategy build from the OpenShift web console as well.

@bparees @jimmidyson

**Comment by bparees** [comment]
the sync plugin should recognize the build object was marked cancelled and do the right thing, like it does when it sees a new build object.

**Comment by jimmidyson** [comment]
Yes - will get to fixing some of these issues tomorrow, hopefully.
