### ISSUE TITLE
Can't run shell command from pipeline

### ISSUE THREAD

**Issue by spadgett** [fabric8io/openshift-jenkins-sync-plugin#60]
This might not be the right repository, but I'm not sure where to track it. I see the following error when I try to run a shell command inside a `node('agent')` block.

```
java.io.IOException: Failed to mkdirs: /home/jenkins/workspace/sample-pipeline/.d8c9f6a5
	at hudson.FilePath.mkdirs(FilePath.java:1163)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.<init>(FileMonitoringTask.java:91)
	at org.jenkinsci.plugins.durabletask.BourneShellScript$ShellController.<init>(BourneShellScript.java:115)
	at org.jenkinsci.plugins.durabletask.BourneShellScript$ShellController.<init>(BourneShellScript.java:110)
```

For instance,

```
node("agent") {
  stage 'Test Shell'
  sh 'echo oops'
}
```

@bparees @jimmidyson

**Comment by bparees** [comment]
I am assuming this error is occurring inside the slave, meaning it relates to the slave image we're using, which is currently "jenkinsci/jnlp-slave"

**Comment by bparees** [comment]
that is configured here:
https://github.com/fabric8io/openshift-jenkins-s2i-config

so that'd probably be the right repo, but i think we can hash it out here.

**Comment by jstrachan** [comment]
I don't think the issue is anything to do with the openshift-jenkins-sync plugin I suspect its related to either the openshift master or jnlp-slave image? I run shell commands all the time in Jenkins with the fabric8 image just fine.

@spadgett do you get different output if you just use `node { ... }` instead of `node("agent") { ... }`?

**Comment by spadgett** [comment]
Right, this is not a sync plugin problem, but I didn't have a place to open the issue. fabric8io/openshift-jenkins-s2i-config doesn't have issues.

It works fine with node { ... }

**Comment by jstrachan** [comment]
gonna close as the fix is to just use `node { ... }`

**Comment by spadgett** [comment]
@jstrachan doesn't that mean I'll only be able to run shell commands on the Jenkins master and not any of the slaves?

**Comment by jstrachan** [comment]
if you want to use the kubernetes plugin you can run things in slaves - though there's not many commands you can run in that (as its a standard fixed image).

Or use the [kubernetes-workflow plugin](https://github.com/fabric8io/kubernetes-workflow/blob/master/kubernetes-steps/readme.md#using-a-maven-kubernetes-pod) to run commands in pods where you can specify the exact docker image + volumes/secrets etc

**Comment by bparees** [comment]
I don't think this should be closed.  If we're going to default a slave image, it should be a slave image that works for this scenario.  Since we don't have control over that slave image, we should be creating our own and providing it.

**Comment by jstrachan** [comment]
this issue has nothing to do with the openshift-jenkins-sync-plugin - it depends on whether you use the kubernetes plugin (with the fixed docker image) or the kubernetes-workflow in the jenkins image from openshift. Probably better to open an issue here instead: https://github.com/openshift/jenkins you can choose what default slaves you want (or kubernetes-workflow plugin or any other jenkins plugins) there

**Comment by bparees** [comment]
@jstrachan my understanding was the image that's being chosen for the slave comes from this configuration:
https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/configuration/config.xml#L49

so as commented above, I agree it's not a sync plugin problem, but i do think it's a problem w/ the default config we're picking up from the openshift-jenkins-s2i-config repo which is configuring the kubernetes plugin to use an image that doesn't work very well.

i'm going to move the discussion there.

**Comment by rawlingsj** [comment]
@bparees FWIW on fabric8 we use our own version of the jnlp client found here https://github.com/fabric8io/jenkins-jnlp-client

You may want to create a few different slaves and then reference them using the pipeline dsl node label..

```
node('maven'){
}
```

```
node('golang'){
}
```

**Comment by rawlingsj** [comment]
The original issue had a problem with the jnlp client?  

The node('agent') refers to the kubernetes-plugin cloud config https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/configuration/config.xml#L55

You can add multiple cloud configs for multiple types of jenkins slaves.

Did the slave actually get created by the example above?  Have you got the whole console log?

**Comment by bparees** [comment]
@rawlingsj i recreated this.  yes the slave pod got (briefly) created.  (pod immediately terminated).

slave container is reporting:
```
WARNING: Failed to resolve a jar 4e35d470bda84437181823f2a58719f1
java.io.IOException: Failed to write to ?/.jenkins/cache/jars/4E/35D470BDA84437181823F2A58719F1.jar
        at hudson.remoting.FileSystemJarCache.retrieve(FileSystemJarCache.java:112)
```

at least that's the error i get.  Given that error, i'm surprised the other slave pod flows actually work.  (even pipelines that execute successfully show that error in their slave container).

the console output is here:
https://gist.github.com/bparees/4fec4ae5577345fa48ec83379b69a61b

**Comment by bparees** [comment]
(i'm sure the issue is that the slave pod is running as a random uid and the image doesn't anticipate that).

**Comment by rawlingsj** [comment]
@bparees ah I think I know what it might be.. it could well be a copy / paste error on my behalf as we use hostvolumes shared with builder pods.

https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/configuration/config.xml#L53

Give me 2 mins and I'll update the config project - BTW I added you as a contributor so you should be able to merge your own commits on https://github.com/fabric8io/openshift-jenkins-s2i-config

**Comment by bparees** [comment]
@rawlingsj ah, yeah that could do it too.  still betting the random uid won't have the right permissions to write to /home/jenkins though, even when it's not a volume.

**Comment by rawlingsj** [comment]
@bparees yeah agreed, it could well be a combination of both.  For now I've just removed that file system mount 

https://github.com/fabric8io/openshift-jenkins-s2i-config/commit/116a99bd4af0783123c855bcc662c47ebac9730d

**Comment by bparees** [comment]
@rawlingsj yeah didn't fix it, but at least the config is cleaner now :)

**Comment by bparees** [comment]
i'm probably going to end up creating our own openshift slave image to solve this, based on what we're doing here already:
https://github.com/openshift/origin/blob/master/examples/jenkins/master-slave/slave/Dockerfile
