### ISSUE TITLE
sync plugin should respect build schedule policy

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#61]
openshift supports 3 scheduling policies for build:
parallel (run any build in the new state)
serial (run a single build at a time, in order)
serial latest (run a single build at a time, skip/cancel intermediate builds when selecting the next build to run)

the sync plugin should reflect those policies (defined on the buildconfig)

This presumably requires syncing the buildconfig setting into the jenkins job config.

**Comment by jstrachan** [comment]
I'm not sure there's Jenkins equivalents to the parallel / serial / serial latest model thats been put into openshift builds?

**Comment by bparees** [comment]
@jstrachan I thought jenkins allows you to configure a job to run in parallel.  the serial-latest probably doesn't exist, but since the sync plugin is what is deciding what to run next, it can implement the logic.

**Comment by bparees** [comment]
(sounds like you need a plugin for parallel behavior:
http://stackoverflow.com/questions/28705222/how-to-run-the-same-job-multiple-times-in-parallel-with-jenkins
)

**Comment by jstrachan** [comment]
sequential / parallel steps are usually steps inside a Jenkinsfile; rather than trying to order independent builds

**Comment by jstrachan** [comment]
indeed, the simplest way to orchestrate multiple builds, is to just create a Jenkinsfile to orchestrate them; you can then define programmatically which steps are sequential, which are parrallel, when to retry and timeout etc

**Comment by bparees** [comment]
@jstrachan what if what i need is to execute my pipeline itself multiple times with different arguments?

suppose my pipeline is a PR testing process.  Every PR opened by users, i want to kick that pipeline off and test the commits in that PR.  I'm not going to parallelize that within my jenkinsfile.

**Comment by jstrachan** [comment]
we use the github PR plugin in jenkins to do just that on all our upstream projects. I'm not 100% sure but it maybe manages this via using different build parameters to ensure that every new build (for a different PR) is run in parallel?

Jenkins users are used to the same build (i.e. the same BuildConfig) not duplicating if its triggered multiple times in quick succession while its pending; folks often use the quiet period settings too so if a number of commits arrive before the build has been scheduled that they are combined into a single build as a way of cutting down noise and redundant builds. If there was no quiet period and if slaves were instantly scheduled I guess things could be really parallel but its not the behaviour I'd expect most Jenkins folks to have really. 

So triggering a jenkins build may not result in a new build (as a subsequent trigger may win) due to quiet period behaviour

**Comment by jimmidyson** [comment]
If an intermediate build is already started, should it be aborted if a new build is requested?

**Comment by bparees** [comment]
no...  we have 3 policies:

1) parallel: run all the builds you want simultaneously
2) serial: wait for each build to complete in order before starting the next
3) seriallatestonly:  wait for the currently running build to complete, cancel all intermediary builds, and run the most recent build request.

theyr'e described in more detail here:
https://docs.openshift.org/latest/dev_guide/builds.html#build-run-policy

**Comment by jimmidyson** [comment]
Sorry I was talking about seriallatestonly! Context, Jimmi, context!

**Comment by bparees** [comment]
yeah, so seriallatestonly still won't cancel a running build, but if it will cancel intermediary builds.

so if you have:
build1(running)
build2(new)
build3(new)

if a new build comes in, you'll have:
build1(running)
build2(new)
build3(new)
build4(new)


when build1 completes, you'll have:
build1(complete)
build2(canceled)
build3(canceled)
build4(running)

it would also be ok to implement it as:
so if you have:
build1(running)
build2(canceled)
build3(new)

if a new build comes in, you'll have:
build1(running)
build2(canceled)
build3(canceled)
build4(new)


when build1 completes, you'll have:
build1(complete)
build2(canceled)
build3(canceled)
build4(running)

**Comment by jimmidyson** [comment]
Brilliant thanks - I'll try to find some time to look at this.

**Comment by bparees** [comment]
(also being tracked as https://bugzilla.redhat.com/show_bug.cgi?id=1356037)

**Comment by jimmidyson** [comment]
Fixed in jenkinsci/openshift-sync-plugin#17

**Comment by jimmidyson** [comment]
Available in release 0.0.16
