### ISSUE TITLE
configure slave namespace on a per job basis 

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#65]
We're going to start defaulting to launch pods in the same namespace as the jenkins master, and allow users to continue to override that value via the jenkins global config, but we're also going to want users to be able to configure the slave namespace at a per job level instead of only at the global config level.

(sorry if you have 3 versions of this issue now, github appears to keep eating them when i open them)

**Comment by jimmidyson** [comment]
Dupe.

**Comment by bparees** [comment]
can you point me to the dupe?

**Comment by bparees** [comment]
oh. i see my other 2 issues finally showed up.
