### ISSUE TITLE
sync plugin launches two pipeline instances

### ISSUE THREAD

**Issue by bparees** [fabric8io/openshift-jenkins-sync-plugin#69]
on several occasions when i start a single pipeline build in openshift, the sync plugin is kicking off two pipeline instances in jenkins.

/cc @sspeiche

**Comment by bparees** [comment]
jenkins logs:
https://gist.github.com/bparees/4884005df21a281a020d9b656bbe5f44

**Comment by spadgett** [comment]
@sg00dwin and @benjaminapetersen have seen this as well. CC @jwforres
