### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by ALRubinger** [fabric8io/openshift-jenkins-sync-plugin#71]
Seems the build is broken; depending upon a SNAPSHOT dependency:

```
[ERROR] Failed to execute goal on project openshift-jenkins-sync-plugin: Could not resolve dependencies for project io.fabric8:openshift-jenkins-sync-plugin:hpi:0.1-SNAPSHOT: Could not find artifact io.fabric8:kubernetes-model:jar:1.0.44-SNAPSHOT in repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/) -> [Help 1]
```

When setting this locally to `io.fabric8:kubernetes-model:jar:1.0.44` I see a compilation error:

```
ERROR] /home/alr/business/jboss/git/fabric8io/openshift-jenkins-sync-plugin/src/main/java/io/fabric8/jenkins/openshiftsync/BuildConfigToJobMapper.java:[29,38] cannot find symbol
[ERROR] symbol:   class JenkinsPipelineBuildStrategy
[ERROR] location: package io.fabric8.openshift.api.model
```

Dependency of my working on #56

**Comment by ALRubinger** [comment]
@jimmidyson We can move this discussion here instead of the MLs; thanks!

**Comment by jimmidyson** [comment]
Sorry my bad. Was depending on snapshot build until Origin 1.3.0-alpha.1 was released & forgot to update after. Will send in fix soon (basically upgrading to latest client version, removing model dependency).

**Comment by ALRubinger** [comment]
Thanks!

**Comment by jimmidyson** [comment]
Build should now be a straight `mvn clean install` to build & `mvn hpi:run` to run Jenkins with the plugin installed.
