### ISSUE TITLE
rogue sync keeps running jobs for a completed pipeline build

### ISSUE THREAD

**Issue by jwforres** [fabric8io/openshift-jenkins-sync-plugin#91]
Not sure what caused this but the second to last pipeline build that ran

![rogue_pipeline](https://cloud.githubusercontent.com/assets/1467629/16238948/a297c8aa-37b0-11e6-941f-aa0fd384db7f.png)

has gone rogue and is continuing to launch jenkins jobs, two of them every hour.

![builds_from_rogue_pipeline](https://cloud.githubusercontent.com/assets/1467629/16238961/b224622e-37b0-11e6-89f9-3a6e333fd3b7.png)

This was on version 0.0.7 of the plugin, I didnt want to blow it away and try the latest yet in case there was anything other debug info you wanted to grab from the project / jenkins.   Here is some of the log from the jenkins pod  https://gist.github.com/jwforres/b8829f3367fe7c3821d571b4f7a1f3b3

**Comment by jwforres** [comment]
@jimmidyson 

cc @spadgett

**Comment by jimmidyson** [comment]
Yeah this has since been fixed - reusing watchers for both new & running builds was the underlying cause.
