### ISSUE TITLE
Propagate pending OpenShift build requests when sync-plugin starts

### ISSUE THREAD

**Issue by ALRubinger** [fabric8io/openshift-jenkins-sync-plugin#93]
Observations:

* OpenShift project is created, and triggers a new build
* Part of the OpenShift project creation is to start a new Jenkins instance
* New build request trigger is fired before Jenkins starts completely
* Build request never reaches Jenkins
* New build requests propogate just fine and start a new Jenkins build

Assuming from this alone, perhaps the sync-plugin is not picking up OpenShift builds currently pending and syncing them to Jenkins?

@jimmidyson

**Comment by jimmidyson** [comment]
When Jenkins starts what is the status of the OpenShift Build? If it's in New phase then it should be picked up by Jenkins.

**Comment by ALRubinger** [comment]
Yep, it's in Status: New. 

![screenshot2](https://cloud.githubusercontent.com/assets/199891/16434099/aaf5fad4-3d5b-11e6-92c4-d6d453017efb.png)

**Comment by ALRubinger** [comment]
![screenshot3](https://cloud.githubusercontent.com/assets/199891/16434103/b3910c92-3d5b-11e6-9695-0233140e8a7a.png)

**Comment by tracyrankin** [comment]
I hit this issue too.  The other thing I noticed is that I'm receiving this error as well on the jenkins pod:

Readiness probe failed: HTTP probe failed with statuscode: 503

**Comment by jimmidyson** [comment]
Readiness probe is unrelated issue - could you please raise an issue for that against https://github.com/openshift/jenkins/issues please?

**Comment by jimmidyson** [comment]
I can't seem to reproduce. Can you share the Jenkins pod logs please?

**Comment by jimmidyson** [comment]
Fixed by jenkinsci/openshift-sync-plugin#7

**Comment by ALRubinger** [comment]
Yeah @jimmidyson !
